<a href="https://colab.research.google.com/github/HariMathivanan/90-s-Portfolio/blob/main/255214336_Ex1_class_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.simplefilter("ignore", DeprecationWarning)

# create a numpy array of 5 integers
arr = np.array([10, 20, 30, 40, 50])
# normalize the array
arr_stand = (arr - arr.mean()) / arr.std()
print(arr_stand)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
# create StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# normalize numpy array
scaler.fit_transform(arr.reshape(-1, 1))
# normalize numpy array
scaler.fit_transform(arr.reshape(-1, 1))

array([[-1.41421356],
       [-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356]])

In [ ]:
# create minmax scaler
from sklearn.preprocessing import MinMaxScaler
min_max = MinMaxScaler()

#normalize numpy arr using minmax scaler
min_max.fit_transform(arr.reshape(-1, 1))

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [ ]:
# Create a dataset with 5 features
# import pandas and its dataframe
import pandas as pd
from pandas import DataFrame
data= {'name':['Rex', 'Peter', 'Sam', 'Rita', 'Hilda'],
'age': [1, 95, 22, 0, 60],
'height':[20, 180, 160, 145,125],
'weight': [0, 100, 75, 55, 40],
'bp': [80, 100, 65, 70, 40]}
#Load data into pandas data frame
frame = DataFrame(data)
print(frame)
#Write dataframe to file
frame.to_csv('patient_data.csv', index=False)
# read file contents back into dataframe
df = pd.read_csv('patient_data.csv')
print(df)
#Replace all zeroes with mean of each column
df = df.replace(0, df.mean(numeric_only = True))
print(df)
#Select all columns except name and create a dataframe
frame2 = df[['age', 'bp', 'height', 'weight']]
print(frame2)
#Apply StandardScaler
scaler.fit(frame2)
# normalize data
scaled = scaler.transform(frame2)
print(scaled)

# print the shape of normalized data
print(scaled.shape)
# print mean and standard deviation values
print("mean : %s " % scaled.mean(axis=0))
print("standard deviation : %s " % scaled.std(axis=0))
#Apply MinMax Scaler
# create another dataframe with all features except name
frame3 = df[['age', 'bp', 'height', 'weight']]
# fit it
print(min_max.fit(frame3))
# normalize it
scaled2 = min_max.transform(frame3)
print(scaled2)
# display mean and standard deviation values
print("mean : %s " % scaled2.mean(axis=0))
print("standard deviation : %s " % scaled2.std(axis=0))
#Select only useful features
from sklearn.feature_selection import VarianceThreshold
# create VarianceThreshold model
sel = VarianceThreshold(threshold=(.5 * (1 - .9)))
#Display preprocessed data based on useful features
useful_features1 = sel.fit_transform(scaled)
print('Useful feature values based on StandardScaler\n')
print(useful_features1)
useful_features2 = sel.fit_transform(scaled2)
print ('\nUseful feature values based on MinMaxScaler')
print(useful_features2)

    name  age  height  weight   bp
0    Rex    1      20       0   80
1  Peter   95     180     100  100
2    Sam   22     160      75   65
3   Rita    0     145      55   70
4  Hilda   60     125      40   40
    name  age  height  weight   bp
0    Rex    1      20       0   80
1  Peter   95     180     100  100
2    Sam   22     160      75   65
3   Rita    0     145      55   70
4  Hilda   60     125      40   40
    name   age  height  weight   bp
0    Rex   1.0      20      54   80
1  Peter  95.0     180     100  100
2    Sam  22.0     160      75   65
3   Rita  35.6     145      55   70
4  Hilda  60.0     125      40   40
    age   bp  height  weight
0   1.0   80      20      54
1  95.0  100     180     100
2  22.0   65     160      75
3  35.6   70     145      55
4  60.0   40     125      40
[[-1.28721689  0.45927933 -1.89346102 -0.51832106]
 [ 1.61303209  1.47990005  0.96459335  1.6893427 ]
 [-0.63928892 -0.30618622  0.60733655  0.48952544]
 [-0.21967843 -0.05103104  0.33939396